//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

// 
// This source code was auto-generated by Microsoft.VSDesigner, Version 4.0.30319.42000.
// 
#pragma warning disable 1591

namespace Liquid.localhost {
    using System;
    using System.Web.Services;
    using System.Diagnostics;
    using System.Web.Services.Protocols;
    using System.Xml.Serialization;
    using System.ComponentModel;
    
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.6.1586.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Web.Services.WebServiceBindingAttribute(Name="TransferManagerSoap", Namespace="http://tempuri.org/")]
    public partial class TransferManager : System.Web.Services.Protocols.SoapHttpClientProtocol {
        
        private System.Threading.SendOrPostCallback HelloWorldOperationCompleted;
        
        private System.Threading.SendOrPostCallback invokeSDKOperationCompleted;
        
        private System.Threading.SendOrPostCallback testOperationCompleted;
        
        private System.Threading.SendOrPostCallback ProcessTransferOperationCompleted;
        
        private System.Threading.SendOrPostCallback PollDBTransferOperationCompleted;
        
        private System.Threading.SendOrPostCallback GenerateGLCodesOperationCompleted;
        
        private System.Threading.SendOrPostCallback ProcessSyncOperationCompleted;
        
        private System.Threading.SendOrPostCallback GenerateInvCodesOperationCompleted;
        
        private System.Threading.SendOrPostCallback ProcessInvSyncOperationCompleted;
        
        private System.Threading.SendOrPostCallback PollDBInvoiceOperationCompleted;
        
        private bool useDefaultCredentialsSetExplicitly;
        
        /// <remarks/>
        public TransferManager() {
            this.Url = global::Liquid.Properties.Settings.Default.Liquid_localhost_TransferManager;
            if ((this.IsLocalFileSystemWebService(this.Url) == true)) {
                this.UseDefaultCredentials = true;
                this.useDefaultCredentialsSetExplicitly = false;
            }
            else {
                this.useDefaultCredentialsSetExplicitly = true;
            }
        }
        
        public new string Url {
            get {
                return base.Url;
            }
            set {
                if ((((this.IsLocalFileSystemWebService(base.Url) == true) 
                            && (this.useDefaultCredentialsSetExplicitly == false)) 
                            && (this.IsLocalFileSystemWebService(value) == false))) {
                    base.UseDefaultCredentials = false;
                }
                base.Url = value;
            }
        }
        
        public new bool UseDefaultCredentials {
            get {
                return base.UseDefaultCredentials;
            }
            set {
                base.UseDefaultCredentials = value;
                this.useDefaultCredentialsSetExplicitly = true;
            }
        }
        
        /// <remarks/>
        public event HelloWorldCompletedEventHandler HelloWorldCompleted;
        
        /// <remarks/>
        public event invokeSDKCompletedEventHandler invokeSDKCompleted;
        
        /// <remarks/>
        public event testCompletedEventHandler testCompleted;
        
        /// <remarks/>
        public event ProcessTransferCompletedEventHandler ProcessTransferCompleted;
        
        /// <remarks/>
        public event PollDBTransferCompletedEventHandler PollDBTransferCompleted;
        
        /// <remarks/>
        public event GenerateGLCodesCompletedEventHandler GenerateGLCodesCompleted;
        
        /// <remarks/>
        public event ProcessSyncCompletedEventHandler ProcessSyncCompleted;
        
        /// <remarks/>
        public event GenerateInvCodesCompletedEventHandler GenerateInvCodesCompleted;
        
        /// <remarks/>
        public event ProcessInvSyncCompletedEventHandler ProcessInvSyncCompleted;
        
        /// <remarks/>
        public event PollDBInvoiceCompletedEventHandler PollDBInvoiceCompleted;
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/HelloWorld", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public string HelloWorld() {
            object[] results = this.Invoke("HelloWorld", new object[0]);
            return ((string)(results[0]));
        }
        
        /// <remarks/>
        public void HelloWorldAsync() {
            this.HelloWorldAsync(null);
        }
        
        /// <remarks/>
        public void HelloWorldAsync(object userState) {
            if ((this.HelloWorldOperationCompleted == null)) {
                this.HelloWorldOperationCompleted = new System.Threading.SendOrPostCallback(this.OnHelloWorldOperationCompleted);
            }
            this.InvokeAsync("HelloWorld", new object[0], this.HelloWorldOperationCompleted, userState);
        }
        
        private void OnHelloWorldOperationCompleted(object arg) {
            if ((this.HelloWorldCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.HelloWorldCompleted(this, new HelloWorldCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/invokeSDK", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public string invokeSDK(string sDataPath) {
            object[] results = this.Invoke("invokeSDK", new object[] {
                        sDataPath});
            return ((string)(results[0]));
        }
        
        /// <remarks/>
        public void invokeSDKAsync(string sDataPath) {
            this.invokeSDKAsync(sDataPath, null);
        }
        
        /// <remarks/>
        public void invokeSDKAsync(string sDataPath, object userState) {
            if ((this.invokeSDKOperationCompleted == null)) {
                this.invokeSDKOperationCompleted = new System.Threading.SendOrPostCallback(this.OninvokeSDKOperationCompleted);
            }
            this.InvokeAsync("invokeSDK", new object[] {
                        sDataPath}, this.invokeSDKOperationCompleted, userState);
        }
        
        private void OninvokeSDKOperationCompleted(object arg) {
            if ((this.invokeSDKCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.invokeSDKCompleted(this, new invokeSDKCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/test", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public string test() {
            object[] results = this.Invoke("test", new object[0]);
            return ((string)(results[0]));
        }
        
        /// <remarks/>
        public void testAsync() {
            this.testAsync(null);
        }
        
        /// <remarks/>
        public void testAsync(object userState) {
            if ((this.testOperationCompleted == null)) {
                this.testOperationCompleted = new System.Threading.SendOrPostCallback(this.OntestOperationCompleted);
            }
            this.InvokeAsync("test", new object[0], this.testOperationCompleted, userState);
        }
        
        private void OntestOperationCompleted(object arg) {
            if ((this.testCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.testCompleted(this, new testCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/ProcessTransfer", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public string[] ProcessTransfer(string sDocNum, string sDocType, string sHistHeader, string sHistLines, string sDataPath, string sSupplRef, string sSOLPMSConn, string sSenderUserCode, string sSenderUserName) {
            object[] results = this.Invoke("ProcessTransfer", new object[] {
                        sDocNum,
                        sDocType,
                        sHistHeader,
                        sHistLines,
                        sDataPath,
                        sSupplRef,
                        sSOLPMSConn,
                        sSenderUserCode,
                        sSenderUserName});
            return ((string[])(results[0]));
        }
        
        /// <remarks/>
        public void ProcessTransferAsync(string sDocNum, string sDocType, string sHistHeader, string sHistLines, string sDataPath, string sSupplRef, string sSOLPMSConn, string sSenderUserCode, string sSenderUserName) {
            this.ProcessTransferAsync(sDocNum, sDocType, sHistHeader, sHistLines, sDataPath, sSupplRef, sSOLPMSConn, sSenderUserCode, sSenderUserName, null);
        }
        
        /// <remarks/>
        public void ProcessTransferAsync(string sDocNum, string sDocType, string sHistHeader, string sHistLines, string sDataPath, string sSupplRef, string sSOLPMSConn, string sSenderUserCode, string sSenderUserName, object userState) {
            if ((this.ProcessTransferOperationCompleted == null)) {
                this.ProcessTransferOperationCompleted = new System.Threading.SendOrPostCallback(this.OnProcessTransferOperationCompleted);
            }
            this.InvokeAsync("ProcessTransfer", new object[] {
                        sDocNum,
                        sDocType,
                        sHistHeader,
                        sHistLines,
                        sDataPath,
                        sSupplRef,
                        sSOLPMSConn,
                        sSenderUserCode,
                        sSenderUserName}, this.ProcessTransferOperationCompleted, userState);
        }
        
        private void OnProcessTransferOperationCompleted(object arg) {
            if ((this.ProcessTransferCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.ProcessTransferCompleted(this, new ProcessTransferCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/PollDBTransfer", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public string[] PollDBTransfer(string sTransNumber) {
            object[] results = this.Invoke("PollDBTransfer", new object[] {
                        sTransNumber});
            return ((string[])(results[0]));
        }
        
        /// <remarks/>
        public void PollDBTransferAsync(string sTransNumber) {
            this.PollDBTransferAsync(sTransNumber, null);
        }
        
        /// <remarks/>
        public void PollDBTransferAsync(string sTransNumber, object userState) {
            if ((this.PollDBTransferOperationCompleted == null)) {
                this.PollDBTransferOperationCompleted = new System.Threading.SendOrPostCallback(this.OnPollDBTransferOperationCompleted);
            }
            this.InvokeAsync("PollDBTransfer", new object[] {
                        sTransNumber}, this.PollDBTransferOperationCompleted, userState);
        }
        
        private void OnPollDBTransferOperationCompleted(object arg) {
            if ((this.PollDBTransferCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.PollDBTransferCompleted(this, new PollDBTransferCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/GenerateGLCodes", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public string[] GenerateGLCodes(string sPastelConn) {
            object[] results = this.Invoke("GenerateGLCodes", new object[] {
                        sPastelConn});
            return ((string[])(results[0]));
        }
        
        /// <remarks/>
        public void GenerateGLCodesAsync(string sPastelConn) {
            this.GenerateGLCodesAsync(sPastelConn, null);
        }
        
        /// <remarks/>
        public void GenerateGLCodesAsync(string sPastelConn, object userState) {
            if ((this.GenerateGLCodesOperationCompleted == null)) {
                this.GenerateGLCodesOperationCompleted = new System.Threading.SendOrPostCallback(this.OnGenerateGLCodesOperationCompleted);
            }
            this.InvokeAsync("GenerateGLCodes", new object[] {
                        sPastelConn}, this.GenerateGLCodesOperationCompleted, userState);
        }
        
        private void OnGenerateGLCodesOperationCompleted(object arg) {
            if ((this.GenerateGLCodesCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.GenerateGLCodesCompleted(this, new GenerateGLCodesCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/ProcessSync", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public string[] ProcessSync(string sGLCode, string sInsertString, string sDataPath, string sSourceRef, string sLiquidConn, string sPastelConn, string sSenderUserCode, string sSenderUserName) {
            object[] results = this.Invoke("ProcessSync", new object[] {
                        sGLCode,
                        sInsertString,
                        sDataPath,
                        sSourceRef,
                        sLiquidConn,
                        sPastelConn,
                        sSenderUserCode,
                        sSenderUserName});
            return ((string[])(results[0]));
        }
        
        /// <remarks/>
        public void ProcessSyncAsync(string sGLCode, string sInsertString, string sDataPath, string sSourceRef, string sLiquidConn, string sPastelConn, string sSenderUserCode, string sSenderUserName) {
            this.ProcessSyncAsync(sGLCode, sInsertString, sDataPath, sSourceRef, sLiquidConn, sPastelConn, sSenderUserCode, sSenderUserName, null);
        }
        
        /// <remarks/>
        public void ProcessSyncAsync(string sGLCode, string sInsertString, string sDataPath, string sSourceRef, string sLiquidConn, string sPastelConn, string sSenderUserCode, string sSenderUserName, object userState) {
            if ((this.ProcessSyncOperationCompleted == null)) {
                this.ProcessSyncOperationCompleted = new System.Threading.SendOrPostCallback(this.OnProcessSyncOperationCompleted);
            }
            this.InvokeAsync("ProcessSync", new object[] {
                        sGLCode,
                        sInsertString,
                        sDataPath,
                        sSourceRef,
                        sLiquidConn,
                        sPastelConn,
                        sSenderUserCode,
                        sSenderUserName}, this.ProcessSyncOperationCompleted, userState);
        }
        
        private void OnProcessSyncOperationCompleted(object arg) {
            if ((this.ProcessSyncCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.ProcessSyncCompleted(this, new ProcessSyncCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/GenerateInvCodes", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public string[] GenerateInvCodes(string sPastelConn) {
            object[] results = this.Invoke("GenerateInvCodes", new object[] {
                        sPastelConn});
            return ((string[])(results[0]));
        }
        
        /// <remarks/>
        public void GenerateInvCodesAsync(string sPastelConn) {
            this.GenerateInvCodesAsync(sPastelConn, null);
        }
        
        /// <remarks/>
        public void GenerateInvCodesAsync(string sPastelConn, object userState) {
            if ((this.GenerateInvCodesOperationCompleted == null)) {
                this.GenerateInvCodesOperationCompleted = new System.Threading.SendOrPostCallback(this.OnGenerateInvCodesOperationCompleted);
            }
            this.InvokeAsync("GenerateInvCodes", new object[] {
                        sPastelConn}, this.GenerateInvCodesOperationCompleted, userState);
        }
        
        private void OnGenerateInvCodesOperationCompleted(object arg) {
            if ((this.GenerateInvCodesCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.GenerateInvCodesCompleted(this, new GenerateInvCodesCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/ProcessInvSync", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public string[] ProcessInvSync(string sInvCode, string sInsertString, string sDataPath, string sSourceRef, string sLiquidConn, string sPastelConn, string sSenderUserCode, string sSenderUserName) {
            object[] results = this.Invoke("ProcessInvSync", new object[] {
                        sInvCode,
                        sInsertString,
                        sDataPath,
                        sSourceRef,
                        sLiquidConn,
                        sPastelConn,
                        sSenderUserCode,
                        sSenderUserName});
            return ((string[])(results[0]));
        }
        
        /// <remarks/>
        public void ProcessInvSyncAsync(string sInvCode, string sInsertString, string sDataPath, string sSourceRef, string sLiquidConn, string sPastelConn, string sSenderUserCode, string sSenderUserName) {
            this.ProcessInvSyncAsync(sInvCode, sInsertString, sDataPath, sSourceRef, sLiquidConn, sPastelConn, sSenderUserCode, sSenderUserName, null);
        }
        
        /// <remarks/>
        public void ProcessInvSyncAsync(string sInvCode, string sInsertString, string sDataPath, string sSourceRef, string sLiquidConn, string sPastelConn, string sSenderUserCode, string sSenderUserName, object userState) {
            if ((this.ProcessInvSyncOperationCompleted == null)) {
                this.ProcessInvSyncOperationCompleted = new System.Threading.SendOrPostCallback(this.OnProcessInvSyncOperationCompleted);
            }
            this.InvokeAsync("ProcessInvSync", new object[] {
                        sInvCode,
                        sInsertString,
                        sDataPath,
                        sSourceRef,
                        sLiquidConn,
                        sPastelConn,
                        sSenderUserCode,
                        sSenderUserName}, this.ProcessInvSyncOperationCompleted, userState);
        }
        
        private void OnProcessInvSyncOperationCompleted(object arg) {
            if ((this.ProcessInvSyncCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.ProcessInvSyncCompleted(this, new ProcessInvSyncCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/PollDBInvoice", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public string[] PollDBInvoice(string sTransNumber) {
            object[] results = this.Invoke("PollDBInvoice", new object[] {
                        sTransNumber});
            return ((string[])(results[0]));
        }
        
        /// <remarks/>
        public void PollDBInvoiceAsync(string sTransNumber) {
            this.PollDBInvoiceAsync(sTransNumber, null);
        }
        
        /// <remarks/>
        public void PollDBInvoiceAsync(string sTransNumber, object userState) {
            if ((this.PollDBInvoiceOperationCompleted == null)) {
                this.PollDBInvoiceOperationCompleted = new System.Threading.SendOrPostCallback(this.OnPollDBInvoiceOperationCompleted);
            }
            this.InvokeAsync("PollDBInvoice", new object[] {
                        sTransNumber}, this.PollDBInvoiceOperationCompleted, userState);
        }
        
        private void OnPollDBInvoiceOperationCompleted(object arg) {
            if ((this.PollDBInvoiceCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.PollDBInvoiceCompleted(this, new PollDBInvoiceCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        public new void CancelAsync(object userState) {
            base.CancelAsync(userState);
        }
        
        private bool IsLocalFileSystemWebService(string url) {
            if (((url == null) 
                        || (url == string.Empty))) {
                return false;
            }
            System.Uri wsUri = new System.Uri(url);
            if (((wsUri.Port >= 1024) 
                        && (string.Compare(wsUri.Host, "localHost", System.StringComparison.OrdinalIgnoreCase) == 0))) {
                return true;
            }
            return false;
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.6.1586.0")]
    public delegate void HelloWorldCompletedEventHandler(object sender, HelloWorldCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.6.1586.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class HelloWorldCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal HelloWorldCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public string Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((string)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.6.1586.0")]
    public delegate void invokeSDKCompletedEventHandler(object sender, invokeSDKCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.6.1586.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class invokeSDKCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal invokeSDKCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public string Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((string)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.6.1586.0")]
    public delegate void testCompletedEventHandler(object sender, testCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.6.1586.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class testCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal testCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public string Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((string)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.6.1586.0")]
    public delegate void ProcessTransferCompletedEventHandler(object sender, ProcessTransferCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.6.1586.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class ProcessTransferCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal ProcessTransferCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public string[] Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((string[])(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.6.1586.0")]
    public delegate void PollDBTransferCompletedEventHandler(object sender, PollDBTransferCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.6.1586.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class PollDBTransferCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal PollDBTransferCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public string[] Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((string[])(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.6.1586.0")]
    public delegate void GenerateGLCodesCompletedEventHandler(object sender, GenerateGLCodesCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.6.1586.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class GenerateGLCodesCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal GenerateGLCodesCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public string[] Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((string[])(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.6.1586.0")]
    public delegate void ProcessSyncCompletedEventHandler(object sender, ProcessSyncCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.6.1586.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class ProcessSyncCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal ProcessSyncCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public string[] Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((string[])(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.6.1586.0")]
    public delegate void GenerateInvCodesCompletedEventHandler(object sender, GenerateInvCodesCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.6.1586.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class GenerateInvCodesCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal GenerateInvCodesCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public string[] Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((string[])(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.6.1586.0")]
    public delegate void ProcessInvSyncCompletedEventHandler(object sender, ProcessInvSyncCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.6.1586.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class ProcessInvSyncCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal ProcessInvSyncCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public string[] Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((string[])(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.6.1586.0")]
    public delegate void PollDBInvoiceCompletedEventHandler(object sender, PollDBInvoiceCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.6.1586.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class PollDBInvoiceCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal PollDBInvoiceCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public string[] Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((string[])(this.results[0]));
            }
        }
    }
}

#pragma warning restore 1591